# SONiC stp package
#

SONIC_STP_VERSION = 1.0.0

SONIC_STP = sonic-stp_$(SONIC_STP_VERSION)_all.deb
$(SONIC_STP)_SRC_PATH = $(SRC_PATH)/sonic-stp
$(SONIC_STP)_WHEEL_DEPENDS += $(SWSSSDK_PY3)
SONIC_DPKG_DEBS += $(SONIC_STP)

export SONIC_STP_VERSION
export SONIC_STP


